version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  judge0:
    image: judge0/judge0:1.13.0
    container_name: judge0
    restart: always
    ports:
      - "2358:2358"

  backend:
    build: ./Backend
    container_name: backend-container
    restart: always
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://myuser:mypass@postgres:5432/mydb
      JUDGE0_URL: http://172.28.235.111:2358
    depends_on:
      - postgres
      - judge0

  frontend:
    build: ./Frontend
    container_name: frontend-container
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata:
